// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4rAu4qV11rLve4NGuxZImujccmzC-UrE',
    appId: '1:777975396721:web:daa2a9edb596b1308aded0',
    messagingSenderId: '777975396721',
    projectId: 'xofthox-45d52',
    authDomain: 'xofthox-45d52.firebaseapp.com',
    storageBucket: 'xofthox-45d52.appspot.com',
    measurementId: 'G-B3MNHPH7Z6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPLpkmyJLmSIGtoShEJT9ft3oU-J8jx38',
    appId: '1:777975396721:android:5877cf029e254e618aded0',
    messagingSenderId: '777975396721',
    projectId: 'xofthox-45d52',
    storageBucket: 'xofthox-45d52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTAhE9xylGGjl8oBYjqLrs7dGAxYPVJN4',
    appId: '1:777975396721:ios:fead5541a48c227e8aded0',
    messagingSenderId: '777975396721',
    projectId: 'xofthox-45d52',
    storageBucket: 'xofthox-45d52.appspot.com',
    iosClientId: '777975396721-r25s4l3loeu0ao8bus2ignhnsk9ufss0.apps.googleusercontent.com',
    iosBundleId: 'com.example.xofthox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTAhE9xylGGjl8oBYjqLrs7dGAxYPVJN4',
    appId: '1:777975396721:ios:fead5541a48c227e8aded0',
    messagingSenderId: '777975396721',
    projectId: 'xofthox-45d52',
    storageBucket: 'xofthox-45d52.appspot.com',
    iosClientId: '777975396721-r25s4l3loeu0ao8bus2ignhnsk9ufss0.apps.googleusercontent.com',
    iosBundleId: 'com.example.xofthox',
  );
}
